### ISSUE TITLE
Building base/orogen/types, and base/types on branch https://github.com/rock-core/base-types/pull/136

### ISSUE THREAD

**Issue by renan028** [rock-core/base-orogen-types#31]
When building base/orogen/types, and base/types on branch: https://github.com/rock-core/base-types/pull/136, I got the error: "The dependency base/types has been built without SISL support. It seems that you have intentially disabled the use of SISL in base/types. While disabling SISL support might be useful for an isolated reuse of base/types, base/orogen/types or more generally the framework Rock strictly requires SISL support in base/types. Please rebuild base/types with -DUSE_SISL=ON").
This is happening because there are changes in base/types master that are not in https://github.com/rock-core/base-types/pull/136. Therefore, I think you just have to merge master in https://github.com/rock-core/base-types/pull/136 (if you don't want to accept the PR right now).

**Comment by doudou** [comment]
PR https://github.com/rock-core/base-types/pull/136 is not necessarily meant to be used directly. The mistake was mine, setting up an override that you can't access and modify as needed.

Best would be to switch to your own fork of base-types until the PR is merged
