### ISSUE TITLE
Missing export of std::vector<base::Time>

### ISSUE THREAD

**Issue by hwiedDFKI** [rock-core/base-orogen-types#33]
Hi,
I want to use std::vector<base::Time> in my Rock-Task. Unfortunately the type is already defined in https://github.com/rock-core/base-types/blob/5cb763997a55d52ae9e6261508c9c8b127cb5e5e/src/JointsTrajectory.hpp#L54, but not exported.
Therefore the type can't be used anywhere else.

Please add the export. :)
Thanks in advance!

**Comment by hwiedDFKI** [comment]
@doudou  ;)

**Comment by 2maz** [comment]
@hwiedDFKI Could you update the export list in base.orogen and open a pull request?

**Comment by hwiedDFKI** [comment]
Like this? https://github.com/rock-core/base-orogen-types/pull/34

**Comment by 2maz** [comment]
Yes, but could you fix the indentation of your addition?!

**Comment by hwiedDFKI** [comment]
Done ;)

**Comment by 2maz** [comment]
Closed by #34
